name: Create Prefect Flow Run

on:
  push:
    branches: [master]
  tags:
    - cloud
  # We would only want to trigger the Flow on push
  # pull_request:
  #   branches: [dev, master]

jobs:
  create_flow_run:
    runs-on: ubuntu-latest

    steps:
      - name: Start Flow
        run: >-
          curl -XPOST
          https://api.prefect.io/graphql
          -H "Authorization: Bearer $PREFECT__GITHUB_ACTIONS_UI_TOKEN"
          -H "Content-type: application/json"
          -d "{\"operationName\":\"CreateFlowRun\",\"variables\":{\"input\": {\"version_group_id\": \"<<TBD>>\", \"parameters\": { \"ref\": \"$REF\" } } }, \"query\":\"mutation CreateFlowRun(\$input: create_flow_run_input!) {create_flow_run(input: \$input) { id } } \"}"

        env:
          PREFECT__GITHUB_ACTIONS_UI_TOKEN: ${{ secrets.PREFECT__GITHUB_ACTIONS_UI_TOKEN }}
          REF: ${{ github.ref }}
